# Generated by Django 2.0.4 on 2018-04-12 14:49

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='image_height_field', null=True, upload_to=posts.models.ImageUpload.get_upload_location, width_field='image_width_field')),
                ('image_width_field', models.IntegerField(default=0)),
                ('image_height_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, to='posts.ImageUpload')),
            ],
        ),
        migrations.CreateModel(
            name='PostKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.PostKey'),
        ),
    ]
